FROM python:3.10-slim

RUN pip3 install dagit dagster-postgres

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

COPY ./ETL /opt/dagster/app/

COPY ETL/dagster.yaml /opt/dagster/dagster_home/dagster.yaml

WORKDIR /opt/dagster/app/

RUN pip3 install -r requirements.txt

EXPOSE 3000

ENTRYPOINT ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]